### ISSUE TITLE
pretrained model？

### ISSUE THREAD

**Issue by Mobu59** [dyhBUPT/StrongSORT#15]
Thanks for your great work. I've been working on a multi-object tracking problem recently, and I've learned a lot from reading your paper. I would like to know if there are demos of pre-trained models and inference custom videos and have you tried using GSI and AFLink for Bytetrack? Looking forward to your reply,Best wishes

**Comment by dyhBUPT** [comment]
Hi, glad to receive your approval for our work.

I'm sorry but we don't have demos for cumtom videos.
I think, maybe, the most contribution of our work is showing some useful tricks and proposing two pulg-and-play modules (AFLink and GSI). So you can try to apply them on other trackers and custom videos by yourself with the help of our code.

For ByteTrack, GSI works, but AFLink doesn't work well. This reflects the limitation of our AFLink. We have made some discussions on this issue in the Section 5.3 and 5.5 in our paper. And we encourage any questions and improvements to our AFLink.

Good luck with your research.
Best wishes.

**Comment by Mobu59** [comment]
Thank you for such a quick reply. In addition, I would like to ask whether GSI is not suitable for online scenarios. As far as I understand, GSI refines the tracking results which is saved as txt file , right? If it's real-time tracking, does GSI work?

**Comment by dyhBUPT** [comment]
You're right. To the best of my knowledge, existing interpolation methods all work in an off-line manner. And both our AFLink and GSI are not suitable for online scenarios.

Best wishes.

**Comment by Edward-YS** [comment]
Hi,
I‘m wondering if there are any possibilities to use GSI in the real-time application.For example,can i use the GSI to interpolate as soon as i get a trace instead of using it until all results produce? Then every time the new trace produces i add it to the results set and update the interpolation processing. Pardon me if this is a fantastic idea.
Or do you have any suggestion to solve trajectory fragmentation in real-time mode?
