### ISSUE TITLE
Is the class id used during tracking?

### ISSUE THREAD

**Issue by Legor** [dyhBUPT/StrongSORT#34]
Hi, thanks for your implementation.
I was wondering if the class id provided by yolo is used in any way during the tracking.
I saw, that the id is stored for each track but I am not sure if it is actually used, e.g. to only match boxes of the same class id?

Also, is it possible to output the class id in the final text file output, i.e. the tracking results.

**Comment by dyhBUPT** [comment]
Hi, glad to see your interest in our work.
The `class id` is not used in our code because we only perform experiments on MOTChallenge dataset which only considers pedestrians. But it seems not so hard to implement it if you want.

And, you can surely output the `class id`. For example, you can pass the `class id` into [`Detection`](https://github.com/dyhBUPT/StrongSORT/blob/dbe13571e841e12003cf993cbbbf55bf6714ea71/deep_sort/detection.py#L5) and save it in the output file. You can see some `-1` in the final [output results](https://github.com/dyhBUPT/StrongSORT/blob/dbe13571e841e12003cf993cbbbf55bf6714ea71/deep_sort_app.py#L218). So, I used to replace some of them with the information I wanted, for example, 'class id' in your case.

I don't know if I'm making myself clear. Please feel free to contact with me if you have any problems.
Best wishes.

**Comment by Legor** [comment]
Hey, thanks for the answer. Yes, that's also what I figured out when reading your code, but thanks for clearing it up anyway.
So far I have trained Yolov5 as well as a reid/feature extractor using my custom data and was able to run StrongSORT using those.

I have the feeling, that I need to optimize some parameters here, especially MC_LAMBDA and EMA_ALPHA. In my application I track animals, which have a low intra class variability, therefor ID switches happen quite often, which I think may be to the similar image features per individual animal. So I would need to dampen the influence of this, which if I understood it right, can be done by choosing a lower MC_LAMBDA ?

Greetings
