### ISSUE TITLE
ID is switch

### ISSUE THREAD

**Issue by YuNaruto** [dyhBUPT/StrongSORT#39]
Hello, I have a problem recently. Is there a better solution?
1. Gray color is the shelter
2. Green color is the tracking target
3. Image frame from 1 to 5
4. The direction of the arrow is to track the moving direction of the object

**Problem: for blocked objects, the tracking frame suddenly changes position, and the ID changes**

The first three frames can be tracked, but the tracking frame is located on the right side of the occlusion (only the exposed part of the green tracking object).

In the fourth frame, the tracking target is completely occluded.

In frame 5, the left part of the tracking object is exposed, but the tracking ID is switched.

This may be because although the first three frames are tracked, the tracking position basically does not change, and then the fifth frame suddenly appears on the left side of the occlusion, resulting in the failure to correlate the Kalman prediction results with the detection results.

![image](https://user-images.githubusercontent.com/32025355/181718609-348cad1a-b07b-44c4-8456-cf15ba18d005.png)

**Comment by dyhBUPT** [comment]
Sorry for my late response. 

It's a good problem~
You're right, it seems that the Kalman Filter fails when the target is **partially occluded** because "the position of the object is not correctly localized by the detector". That's, the bounding box doesn't accurately reflect the **center** and the **h/w** of the target.

So now, maybe you have two ways:
1. think how to accurately localize the  true **x,y,w,h** of the target.
2. reduce the reliance on the motion information and associate it based on appearance features.

I'll be glad if you can share with me your other ideas or the final successful solutions.
Best wishes.

**Comment by YuNaruto** [comment]
Use the mean value of the N frames before the loss, then EMA, and finally use mean [2:], that is, R H V_ x v_ y v_ r v_ h。
It is helpful for similar problems such as inaccurate Kalman filter caused by inaccurate detection results.
In addition, for the two-way traffic, the big car blocks the small car, which has a good effect.

**Comment by dyhBUPT** [comment]
Thanks for your sharing!
