### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by sasakits** [dyhBUPT/StrongSORT#5]
Thank you for your great work.

Do you have the plan to implement code for demo?

**Comment by dyhBUPT** [comment]
Thanks for your interest in our work.
I'm sorry but it's a little hard to implement a simple demo code because the entire framework consists of various components, i.e., detection, feature extraction, CMC and tracking.
We only provide the tracking code and results of other components on MOT17 and MOT20 now.
If you are insterested in a demo result, the simplest way would be to visit the MOTChallenge website and find the visualization results of our method on MOT17 and MOT20 test set, i.e., https://motchallenge.net/method/MOT=4710&chl=10
