### ISSUE TITLE
关于ecc生成json文件的问题

### ISSUE THREAD

**Issue by godHhh** [dyhBUPT/StrongSORT#59]
您好，您做了一项非常棒的工作，我目前正在学习您的代码。我在生成ECC文件时，出现了一个这样的错误，我不知道如何解决，请您赐教。愿您能回复我，best wishes to you!
![image](https://user-images.githubusercontent.com/47073050/210055975-359d4d02-38f2-4a55-a3ec-540c1c0c1f2b.png)

cv2.error: OpenCV(4.6.0) /io/opencv/modules/video/src/ecc.cpp:589: error: (-7:Iterations do not converge) The algorithm stopped before its convergence. The correlation is going to be minimized. Images may be uncorrelated or non-overlapped in function 'findTransformECC'

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.
It's the same issue as https://github.com/dyhBUPT/StrongSORT/issues/16.

I think it's caused by the out-of-order images. Please debug to see the real reason.

Maybe you can try to modify this line to make sure that your images are read in turn:
https://github.com/dyhBUPT/StrongSORT/blob/efc79c21182736a8a21c32f4f2114a57fc812dac/others/ecc.py#L163

Please let me know if this works.
Best  wishes.

**Comment by godHhh** [comment]
感谢您的帮助，问题解决好啦，代码163行后加上pictures = sorted(pictures) 成功解决！
Best wishes.

**Comment by dyhBUPT** [comment]
Glad to hear that ~
