### ISSUE TITLE
ECC JSON files for MOT17 and MOT20 training data

### ISSUE THREAD

**Issue by kamkyu94** [dyhBUPT/StrongSORT#7]
Hello. Thank you for your astonishing work!

By the way, can you also share ECC JSON files for MOT17 and MOT20 training data?

Thank you.

**Comment by dyhBUPT** [comment]
We didn't provide the ECC JSON for the training set because it's unreasonable to run tracking on it (because we use it to train our detector).
By the way, the camera barely moves in MOT20, so you may don't need the ECC JSON for MTO20. 
Even so, if you really need the ECC results on the training set, please tell me. And we will provide them in our data link.
