### ISSUE TITLE
KeyError: 'MOTChallenge\\MOT17\\train\\MOT17-02-FRCNN'

### ISSUE THREAD

**Issue by buyi6666** [dyhBUPT/StrongSORT#70]
Thank you for your great work !

When I run  `strong_sort.py MOT17 val --BoT --ECC --NSA --EMA --MC --woC` ,
 it displays
 ```
StrongSORT-master\deep_sort\track.py", line 141, in camera_update dict_frame_matrix =opt.ecc[video]
KeyError: 'MOTChallenge\\MOT17\\train\\MOT17-02-FRCNN'
```
Why does it happen ?

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

It seems that the error is caused by the wrong param `video` passed to `camera_update`:
https://github.com/dyhBUPT/StrongSORT/blob/666e7f3399808b57e310722670c5f059810954b3/deep_sort/track.py#L140

Ideally, the `video` should be `MOT17-02-FRCNN`, not `MOTChallenge\\MOT17\\train\\MOT17-02-FRCNN`.
It may be caused by using Windows, instead of Linux.

For this error, you can try to modify this code line:
https://github.com/dyhBUPT/StrongSORT/blob/666e7f3399808b57e310722670c5f059810954b3/deep_sort_app.py#L187

Best wishes.

**Comment by buyi6666** [comment]
Thank you for your reply!
I modified it and solved the problem.
`tracker.camera_update(sequence_dir.split('\\')[-1], frame_idx)`
Thank you very much!
