### ISSUE TITLE
Feature extractor weights

### ISSUE THREAD

**Issue by IrinaMonaEpure** [dyhBUPT/StrongSORT#81]
Thank you very much for all your work on this great repository! 

I was wondering whether you could make available some resources that I have not been able to find yet:
- the .pth weights and .yml file corresponding to the feature extraction model you used, or
- the features extracted on MOT20 train (as all the other features are already there).

Is there any reason in particular why you decided not to include the features of MOT20 train in your Drive folder?

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

- The `.yml` file is the same as https://github.com/JDAI-CV/fast-reid/blob/master/configs/DukeMTMC/bagtricks_S50.yml.
- The `.pth` file was uploaded to the google drive named `DukeMTMC_BoT-S50.pth` just now.
- The features of MOT20 is not included because we didn't conduct ablation experimens on MOT20. We use the exact same hyper-paremeters for MOT20 as that in MOT17.

Best wishes.
