### ISSUE TITLE
Question about the result on Dancetrack dataset

### ISSUE THREAD

**Issue by Sheldon-Zheng** [dyhBUPT/StrongSORT#85]
Could you provide more details about the algorithm settings of the Strongsort for the Dancetrack？I find it hard to get the satisfying result you mentioned in the paper with only changing some parameters of it.

**Comment by dyhBUPT** [comment]
Hi, the StrongSORT on DanceTrack has no essential differences with this repo.
We use the raw simple CNN in DeepSORT to extract features, and EMA is not used.
The consine threshold is 0.3, the `lambda` for motion_cost is 0.98;
the parameter for AFLink is thrT=(0,30), thrS=75, thrP=0.1;
the parameter for GSI is interval=5, tau=10.

Please note that, in our experiments, to make interpolation (linear & GSI) work, you need to set `track.time_since_update > 0` insted of `track.time_since_update > 1` in https://github.com/dyhBUPT/StrongSORT/blob/ad7d143f1ecaa1cf654300e3e3d2daf937b0a997/deep_sort_app.py#L202
Moreover, it's recommended to use detection results as the tracking results, instead of the updated bboxes from Kalman Filter.

Please try it, and you can also explore more ablation study and parameter-tuning experiments. Looking forward to your sharing new results.

**Comment by Sheldon-Zheng** [comment]
Thanks!
